approve_by_comment: true
approve_regex: ^LGTM
reject_regex: ^Rejected
reset_on_push: false
author_approval: ignored
reviewers:
  members:
  - basicthinker
  - hqd2009
  - james0zan
  name: pullapprove
  required: 2
