language: c
compiler: gcc
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install -yq cmake
 - sudo apt-get install -yq zlib1g-dev
 - wget https://github.com/pmem/nvml/releases/download/1.1/nvml-1.1-dpkgs.tar.gz
 - tar zxvf nvml-*.tar.gz
 - sudo dpkg -i libpmem_*_amd64.deb
 - sudo dpkg -i libpmem-dev_*_amd64.deb
script:
 - mkdir build; cd build
 - cmake ../
 - make
 - make test
